apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: demo-route
  namespace: foobar
spec:
  host: demo.apps.cluster1.ocp.lab.ip
  to:
    kind: Service
    name: demo-service
  port:
    targetPort: demo-ports
